### ISSUE TITLE
Error is returned despite successful fetching of attestation document

### ISSUE THREAD

**Issue by NullHypothesis** [hf/nsm#2]
I obtained an attestation document as [outlined in the README](https://github.com/hf/nsm#obtaining-an-attestation-document). The call `sess.Send()` returned an error even though it successfully managed to retrieve an attestation document because of the following:

`cbor.Unmarshal` [returns an error](https://github.com/hf/nsm/blob/83437edcd7fc96e99b5d204b393e099567cc34bd/response/response.go#L105), so the code tries again, with a map instead of a string. The second call to `cbor.Unmarshal` [succeeds](https://github.com/hf/nsm/blob/83437edcd7fc96e99b5d204b393e099567cc34bd/response/response.go#L108), after which the code populates the attestation document. The code returns an error regardless because the string [was not populated earlier](https://github.com/hf/nsm/blob/83437edcd7fc96e99b5d204b393e099567cc34bd/response/response.go#L126).

I'm not particularly familiar with CBOR or AWS's NSM but it looks like we shouldn't return an error if the string was empty as long as the map was populated successfully?

**Comment by hf** [comment]
This should be fixed with #3. Thanks for catching it!
